name: Docker Build Pull Requests

on:
  push:
    branches:
    - '!main'
  pull_request:
    branches:
    - '**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Build
      run: |
        docker build --tag levelupdevopspr:${{ github.sha }} .
